config/routes.rb
Rails.application.routes.draw do
  
  resources :apps do
     resources :things
  end
  resources :relations
 
  resources :properties
  resources :types

  root 'apps#index'

end

app/models/app_thing.rb
class AppThing < ActiveRecord::Base
  belongs_to :app
  belongs_to :thing
end

app/helpers/app_things_helper.rb
module AppThingsHelper
end

app/views/app_things/_app_thing.html.erb
<tr class="fields">
    <td><%= app_thing.thing.name%></td>
    <td>
    	<%= link_to 'Eliminar', app_thing, method: :delete, data: { confirm: 'Estas seguro?' }, remote: true  %>
    </td>
 </tr>

app/views/app_things/_form.html.erb
<%= simple_form_for(@app_thing) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.association :app %>
    <%= f.association :thing %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/app_things/edit.html.erb
<h1>Editing App Thing</h1>

<%= render 'form' %>

<%= link_to 'Show', @app_thing %> |
<%= link_to 'Back', app_things_path %>

app/views/app_things/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing App Things</h1>

<table>
  <thead>
    <tr>
      <th>App</th>
      <th>Thing</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @app_things.each do |app_thing| %>
      <tr>
        <td><%= app_thing.app %></td>
        <td><%= app_thing.thing %></td>
        <td><%= link_to 'Show', app_thing %></td>
        <td><%= link_to 'Edit', edit_app_thing_path(app_thing) %></td>
        <td><%= link_to 'Destroy', app_thing, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New App thing', new_app_thing_path %>

app/views/app_things/new.html.erb
<h1>New App Thing</h1>

<%= render 'form' %>

<%= link_to 'Back', app_things_path %>

app/views/app_things/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>App:</strong>
  <%= @app_thing.app %>
</p>

<p>
  <strong>Thing:</strong>
  <%= @app_thing.thing %>
</p>

<%= link_to 'Edit', edit_app_thing_path(@app_thing) %> |
<%= link_to 'Back', app_things_path %>