config/routes.rb
Rails.application.routes.draw do
  
  resources :apps do
     resources :things
  end
  resources :relations
 
  resources :properties
  resources :types

  root 'apps#index'

end

app/models/thing.rb
class Thing < ActiveRecord::Base
	
	has_many :properties
	has_many :relations
	belongs_to :app
	
	#validates :name, presence: true, uniqueness: true
  	
  	accepts_nested_attributes_for :properties, :reject_if  => :all_blank, update_only: true
  	accepts_nested_attributes_for :relations, :reject_if  => :all_blank, update_only: true


end

app/controllers/things_controller.rb
class ThingsController < ApplicationController
  before_action :set_thing, only: [:show, :edit, :update, :destroy]
  before_action :set_app, only: [:edit, :show, :new, :create,:update, :destroy]

  # GET /things
  # GET /things.json
  def index
    @things = Thing.all
  end

  # GET /things/1
  # GET /things/1.json
  def show
  end

  # GET /things/new
  def new
    @thing = Thing.new
  end

  # GET /things/1/edit
  def edit
  end

  # POST /things
  # POST /things.json
  def create
    @thing = @app.things.build(thing_params)

    respond_to do |format|
      if @thing.save
        format.html { redirect_to app_thing_path(@app,@thing), notice: 'Thing was successfully created.' }
        format.json { render :show, status: :created, location: @thing }
      else
        format.html { render :new }
        format.json { render json: @thing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /things/1
  # PATCH/PUT /things/1.json
  def update
    respond_to do |format|
      if @thing.update(thing_params)
        format.html { redirect_to app_thing_path(@app,@thing), notice: 'Thing was successfully updated.' }
        format.json { render :show, status: :ok, location: @thing }
      else
        format.html { render :edit }
        format.json { render json: @thing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /things/1
  # DELETE /things/1.json
  def destroy
    @thing.destroy
    respond_to do |format|
      format.html { redirect_to app_thing_path(@app,@thing), notice: 'Thing was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_thing
      @thing = Thing.find(params[:id])
    end

    def set_app
      @app = App.find(params[:app_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def thing_params
      params.require(:thing).permit(:name,:description, properties_attributes: [:id, :name, :type_id, :_destroy], relations_attributes: [:id, :related_to_thing_id, :_destroy, :association_type])
    end
end

app/helpers/things_helper.rb
module ThingsHelper
end

app/views/things/_form.html.erb
<%=simple_form_for([@app, @thing]) do |f| %>
<%= f.error_notification %>
<%= f.input :name %>
<%= f.input :description %>
<%= f.submit "Guardar" %>
<% end %>

app/views/things/_property_fields.html.erb
<tr class="fields">
    <%= f.hidden_field :id, label:false %>
    <%= f.hidden_field :_destroy %>
    <td><%= f.input :name, label:false %></td>
    <td><%= f.association :type, label:false, :collection => Type.all, prompt: "Tipo de dato", :label_method => :name, :value_method => :id %></td>
    <td>
    	<% unless f.object.id %>
    	<%= link_to_remove_fields "remove", f %>
    	<% else %>
    	<%= link_to 'Eliminar', f.object, method: :delete, data: { confirm: 'Estas seguro?' }, remote: true  %>
    	<% end %>
    </td>
 </tr>

app/views/things/_relation_fields.html.erb
<tr class="fields">
    <%= f.hidden_field :id, label:false %>
    <%= f.hidden_field :_destroy %>
    <td><%= f.input :association_type, label:false, collection: Relation::ASSOCIATIONS_TYPE %></td>
    <td><%= f.association :related_to_thing, label:false, :collection => Thing.all, prompt: "Tipo de Objeto", :label_method => :name, :value_method => :id %></td>
    <td>
    	<% unless f.object.id %>
    	<%= link_to_remove_fields "remove", f %>
    	<% else %>
    	<%= link_to 'Eliminar', f.object, method: :delete, data: { confirm: 'Estas seguro?' }, remote: true  %>
    	<% end %>
    </td>
 </tr>

app/views/things/edit.html.erb
 <%= link_to 'Atrás', app_path(@app) %>
 <div class="row">
    <div class="col-md-10"><h1 class="page-header">Editar Modelo</h1></div>
    <div class="col-md-2 text-right"><%=image_tag("thing.jpeg", height: '50', width: '50', class: "img-responsive", alt: "Generic placeholder thumbnail" )%></div>
  </div>
<%= render 'form' %>

app/views/things/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listado de Clases </h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @things.each do |thing| %>
      <tr>
        <td><%= thing.name %></td>
        <td><%= link_to 'Ver', thing %></td>
        <td><%= link_to 'Editar', edit_thing_path(thing) %></td>
        <td><%= link_to 'Eliminar', thing, method: :delete, data: { confirm: 'Esta seguro?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nueva Clase', new_thing_path %>

app/views/things/new.html.erb
 <%= link_to 'Atrás', app_path(@app) %>
 <div class="row">
    <div class="col-md-10"><h1 class="page-header">Nuevo Modelo</h1></div>
    <div class="col-md-2 text-right"><%=image_tag("thing.jpeg", height: '50', width: '50', class: "img-responsive", alt: "Generic placeholder thumbnail" )%></div>
  </div>
 <%= render 'form' %>

app/views/things/show.html.erb
<p>
  <strong>Modelo:</strong>
</p>
<p>
<%= @thing.name %>
</p>
<p>

<%= link_to 'Edit', edit_app_thing_path(@app,@thing) %> |
<%= link_to 'Back', app_path(@app) %>