config/routes.rb
Rails.application.routes.draw do
  
  resources :apps do
     resources :things
  end
  resources :relations
 
  resources :properties
  resources :types

  root 'apps#index'

end

app/views/apps/_app_thing_fields.html.erb
<tr class="fields">
    <%= f.hidden_field :id, label:false %>
    <%= f.hidden_field :_destroy %>
    <td><%= f.association :thing, label:false, :collection => Thing.all, prompt: "Tipo de Objeto", :label_method => :name, :value_method => :id %></td>
    <td>
    	<% unless f.object.id %>
    	<%= link_to_remove_fields "Eliminar", f %>
    	<% end %>
    </td>
 </tr>

app/views/apps/_form.html.erb
<%= simple_form_for(@app) do |f| %>
<%= f.error_notification %>
<%= f.input :name %>
<%= f.input :description %>
<%= f.button :submit , "Guardar"%>
<% end %>

app/views/apps/edit.html.erb
<h1>Editing App</h1>

<%= render 'form' %>

<%= link_to 'Show', @app %> |
<%= link_to 'Back', apps_path %>

app/views/apps/index.html.erb
 <h1 class="page-header">Proyectos <%= link_to '+', new_app_path , class: "btn btn-sm btn-default" %></h1>
 <div class="row placeholders">
  <% @apps.each do |app| %>
  <div class="col-sm-2 placeholder">
    <%= link_to(image_tag("project.jpeg", height: '100', width: '100', class: "img-responsive", alt: "Generic placeholder thumbnail" ),app) %>
    <h4><%= app.name %></h4>
    <span class="text-muted"><%= app.description %></span>
  </div>
  <% end %>
</div>

app/views/apps/new.html.erb
 <%= link_to 'Atrás', apps_path %>
 <h1 class="page-header">Nuevo Proyecto</h1>
 <%= render 'form' %>

app/views/apps/show.html.erb
<%= link_to 'Atrás', apps_path %>
<h1 class="page-header"><%= @app.name %></h1>
<h1><small>Modelos <%= link_to '+', new_app_thing_path(@app) , class: "btn btn-xs btn-default" %></small></h1>
<div class="row placeholders">
  <% @app.things.each do |thing| %>
  <div class="col-sm-2 placeholder">
    <%= link_to(image_tag("thing.jpeg", height: '100', width: '100', class: "img-responsive", alt: "Generic placeholder thumbnail" ),app_thing_path(@app,thing )) %>
    <h4><%= thing.name %></h4>
    <span class="text-muted"><%= thing.description %></span>
  </div>
  <% end %>
</div>